### ISSUE TITLE
.cached  - - - > cached( )

### ISSUE THREAD

**Issue by sumith1896** [ravimad/Orb2015#26]
@ravimad we need this change right?

**Comment by ravimad** [comment]
yes. right, not very critical though

**Comment by sumith1896** [comment]
I'm planning of doing `time` to `steps`, should I do them both and send a PR?

**Comment by ravimad** [comment]
Okay. But, the block diagram is more pressing now ;-)

**Comment by sumith1896** [comment]
Cool. Will get that done first.

**Comment by ravimad** [comment]
Great. Try to use a tixz package

**Comment by sumith1896** [comment]
Fixed
